In [31]:
from keras.datasets import mnist

In [32]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [33]:
train_images.shape

(60000, 28, 28)

In [34]:
len(train_labels)

60000

In [35]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [36]:
test_images.shape

(10000, 28, 28)

In [37]:
len(test_labels)

10000

In [38]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [39]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

The compilation step

In [40]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

Preparing the image data in correct format

In [41]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [47]:
train_images.shape

(60000, 784)

In [48]:
test_images.shape

(10000, 784)

Preparing the labels

In [44]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

Training the network

In [50]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 1s 25us/step - loss: 0.0073 - acc: 0.9979
Epoch 2/5
60000/60000 [==============================] - 1s 23us/step - loss: 0.0058 - acc: 0.9984
Epoch 3/5
60000/60000 [==============================] - 1s 24us/step - loss: 0.0047 - acc: 0.9987
Epoch 4/5
60000/60000 [==============================] - 1s 23us/step - loss: 0.0038 - acc: 0.9990
Epoch 5/5
60000/60000 [==============================] - 1s 22us/step - loss: 0.0030 - acc: 0.9992


In [53]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test acc:', test_acc)

10000/10000 [==============================] - 0s 30us/step
test acc: 0.9796


In [59]:
import numpy as np
x = np.array(10)
x

array(10)

In [60]:
x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

In [61]:
x.ndim

1

In [65]:
x = np.array([
                [5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 2]
            ])

In [66]:
x.shape

(3, 5)

In [67]:
x.ndim

2